class_name ChangeBonesAction
extends Action

var amount: int
var player_id: String
## If this bone generated by a card death this is the card id. Is null if bone is gain not from
## death
var death_source_id: String


static func action_type() -> Type:
	return Action.Type.CHANGE_BONES


func _init(a: int, pid: String, dsid: String = "") -> void:
	amount = a
	player_id = pid
	death_source_id = dsid


func resolve(fight_manager: FightManager) -> void:
	if amount == 0:
		fight_manager._no_activation()
		return
	var data := fight_manager.get_data(player_id)
	data.bones += amount
	var card := fight_manager.card_manager.get_card_by_id(death_source_id)
	await fight_manager._activate_hooks(
		func(hook: ActionHook) -> void: hook.on_bone_changed(amount, player_id, card)
	)


func as_dict() -> Dictionary:
	return {
		type = action_type(),
		amount = amount,
		player_id = player_id,
		death_source_id = death_source_id
	}


static func from_dict(dict: Dictionary) -> Action:
	return ChangeBonesAction.new(
		dict.amount as int, dict.player_id as String, dict.death_source_id as String
	)
